### ISSUE TITLE
Add social Links

### ISSUE THREAD

**Issue by thevinitgupta** [thevinitgupta/Portfolio#1]
Add social links that appear as **HORIZONTAL LOLLIPOP**

### Tasks :

- [ ] Make a social component
- [ ] Have a prop that accepts the icon name 
- [ ] Add animation on load using life cycle hooks to slide from right
- [ ] Add hover animation to rotate 360deg 2 times
